REMOTE_URL =    "http://127.0.0.1:4723"        
PLATFORM_NAME =  "Android"
PLATFORM_VERSION = "14"
DEVICE_NAME =     "R92XA1SLC8W"
APP_PACKAGE =          "sn.sonatel.dsi.moussa.wade.moussawade"
APP_ACTIVITY   =    ".MainActivity"
AUTOMATION_NAME = "uiautomator2"
